# source TFRecord dataset directory
src_tfrec_dir: /Users/agiri1/Desktop/ExoBD_Datasets
# table that contains the order of the examples in the TFRecord files in the data set
shards_tbl_fp: /Users/agiri1/Desktop/ExoBD_Datasets/shards_tbl.csv
# directory with tables used to split the examples into different sets (train, validation, test, predict, ...)
split_tbls_dir: /Users/agiri1/Desktop/ExoBD_Datasets/train_test_split
# defines which tables are used and the prefix of the TFRecord shards; e.g., if train split table is loaded, it will
# put all examples from that table that can find in the shards in the source TFRecord dataset into shards starting with
# the prefix `train-shard`
datasets:
  - train
  - val
  - test
 # - predict
omitMissing: True  # skip missing TCEs in the TFRecords that exist in the dataset tables
nProcesses: 10  # number of processes used to create the new TFRecord dataset
n_examples_per_shard: 100  # number of examples in each shard in the new TFRecord dataset; min(n_examples_per_shard, n_total_examples)
# destination directory
dest_tfrec_dir: /Users/agiri1/Desktop/ExoBD_Datasets/shards
verbose: true
