# source TFRecord directory
tfrecDir: /Users/msaragoc/Projects/exoplanet_transit_classification/data/tfrecords/tess/tfrecords_tess_s1-s67_10-31-2023_1452_data/tfrecords_tess_s1-s67_10-31-2023_1452_magshift_mission_adddiffimg_dataset_split
# destination directory for computed statistics
norm_dir: /Users/msaragoc/Projects/exoplanet_transit_classification/data/tfrecords/tess/tfrecords_tess_s1-s67_10-31-2023_1452_data/tfrecords_tess_s1-s67_10-31-2023_1452_magshift_mission_adddiffimg_dataset_split

n_processes_compute_norm_stats: 10  # number of processes used to parallelize reading the values for the dataset

clip_value_centroid: 30  # in arcsec; 115.5 and 30 arcsec for TESS and Kepler, respectively

# get out-of-transit indices for the local and global views
nr_transit_durations: 5  # number of transit durations in the local view
num_bins_loc: 31  # number of bins for local view
num_bins_glob: 301  # number of bins for global view

timeSeriesFDLList: null
#  - 'global_centr_fdl_view'
#  - 'local_centr_fdl_view'

centroidList:
  - 'global_centr_view'
  - 'local_centr_view'

diff_imgList: # null
  - 'diff_imgs'
  - 'oot_imgs'

# dictionary that provides information on the normalization specificities for each scalar parameters (e.g., placeholder
# for missing value other than NaN, perform log-transform, clipping factor, data type, replace value for missing value)
# comment/add scalar parameters that are not/are part of the source TFRecords
scalarParams:

  # bootstrap FA prob
  boot_fap: # feature name
    clip_factor: 20  # .nan  # values are truncated to  median +- mad_std * clip_factor; if .nan, values are not truncated
    dtype: float  # feature data type; mostly `float`
    log_transform: true  # if true, values are log-transformed
    log_transform_eps: 1.0e-32  # log-transform offset factor to prevent invalid log(0)
    missing_value: -1  # placeholder value for missing values; if missing value is represented by  NaN or there are no missing values, set to null
    replace_value: null  # value used to replace missing value; if null, missing values are replaced by median of the training set
    standardize: true

  # odd-even
  odd_se_oot:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  odd_std_oot_bin:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  even_se_oot:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  even_std_oot_bin:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_bin_oedp_stat:
    clip_factor: 400
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true

  # centroid
  tce_dicco_msky:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_dicco_msky_err:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: -1
    replace_value: null
    standardize: true
  tce_dikco_msky:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_dikco_msky_err:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: -1
    replace_value: null
    standardize: true
#  tce_fwm_stat:  # Kepler only
#    clip_factor: 20
#    dtype: float
#    log_transform: false
#    log_transform_eps: .nan
#    missing_value: 0
#    replace_value: null
#    standardize: true

  # ghost diagnostics
  tce_hap_stat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_cap_stat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true

  # rolling band
#  tce_rb_tcount0n:  # Kepler only
#    clip_factor: .nan
#    dtype: float
#    log_transform: false
#    log_transform_eps: .nan
#    missing_value: null
#    replace_value: null
#    standardize: true

  # stellar parameters
  tce_sdens:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_slogg:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_smass:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_smet:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_sradius:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_steff:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  ruwe:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: 0
    standardize: true
  mag:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  mag_shift:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  mag_cat:
    clip_factor: .nan
    dtype: float  # int
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: false

  # secondary parameters
  tce_maxmes:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  wst_depth:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: 0
    standardize: true
  tce_ptemp_stat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_albedo_stat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true

  # TCE parameters
  tce_depth:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_robstat: # not available for Kepler simulated data
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_max_mult_ev:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_max_sngle_ev:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_model_chisq:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: -1
    replace_value: null
    standardize: true
  tce_period:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_prad:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_num_transits:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
