# source TFRecord directory
tfrecDir: /data5/tess_project/Data/tfrecords/Kepler/Q1-Q17_DR25/tfrecordskeplerq1q17dr25-dv_g301-l31_5tr_spline_nongapped_4-6-2022_data/tfrecordskeplerq1q17dr25-dv_g301-l31_5tr_spline_nongapped_4-6-2022_uid_experiment

nProcesses: 15  # number of processes used to parallelize reading the values for the dataset

clip_value_centroid: 30  # in arcsec; 115.5 and 30 arcsec for TESS and Kepler, respectively

# get out-of-transit indices for the local and global views
nr_transit_durations: 5  # number of transit durations in the local view
num_bins_loc: 31  # number of bins for local view
num_bins_glob: 301  # number of bins for global view

# dictionary that provides information on the normalization specificities for each scalar parameters (e.g., placeholder
# for missing value other than NaN, perform log-transform, clipping factor, data type, replace value for missing value)
# comment/add scalar parameters that are not/are part of the source TFRecords
scalarParams:
  boot_fap: # feature name
    clip_factor: 20  # .nan  # values are truncated to  median +- mad_std * clip_factor; if .nan, values are not truncated
    dtype: float  # feature data type; mostly `float`
    log_transform: true  # if true, values are log-transformed
    log_transform_eps: 1.0e-32  # log-transform offset factor to prevent invalid log(0)
    missing_value: -1  # placeholder value for missing values; if missing value is represented by  NaN or there are no missing values, set to null
    replace_value: null  # value used to replace missing value; if null, missing values are replaced by median of the training set
    standardize: true
  even_se_oot:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  even_std_oot_bin:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  mag:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  mag_cat:
    clip_factor: .nan
    dtype: int
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: false
  odd_se_oot:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  odd_std_oot_bin:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_albedo_stat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_bin_oedp_stat:
    clip_factor: 400
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_cap_hap_stat_diff:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_cap_stat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_dicco_msky:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_dicco_msky_err:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: -1
    replace_value: null
    standardize: true
  tce_dikco_msky:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_dikco_msky_err:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: -1
    replace_value: null
    standardize: true
  tce_fwm_stat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_hap_stat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_max_mult_ev:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_max_sngle_ev:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_model_chisq:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: -1
    replace_value: null
    standardize: true
  tce_maxmes:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_period:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_prad:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_ptemp_stat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: null
    standardize: true
  tce_rb_tcount0n:
    clip_factor: .nan
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_robstat:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_sdens:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_slogg:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_smass:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_smet:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_sradius:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  tce_steff:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  transit_depth:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: null
    replace_value: null
    standardize: true
  wst_depth:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: 0
    standardize: true
  ruwe:
    clip_factor: 20
    dtype: float
    log_transform: false
    log_transform_eps: .nan
    missing_value: 0
    replace_value: 0
    standardize: true
