# source TFRecord dataset directory
src_tfrec_dir: /Users/msaragoc/Projects/exoplanet_transit_classification/data/tfrecords/tess/tfrecords_tess_s1-s67_10-31-2023_1452_magshift_mission_adddiffimg
# table that contains the order of the examples in the TFRecord files in the data set
shards_tbl_fp: /Users/msaragoc/Projects/exoplanet_transit_classification/data/tfrecords/tess/tfrecords_tess_s1-s67_10-31-2023_1452_magshift_mission_adddiffimg/shards_tbl.csv
# directory with tables used to split the examples into different sets (train, validation, test, predict, ...)
split_tbls_dir: /Users/msaragoc/Projects/exoplanet_transit_classification/data/dataset_splits/tess/split_tess_s1-s67_11-29-2023_2159
# defines which tables are used and the prefix of the TFRecord shards; e.g., if train split table is loaded, it will
# put all examples from that table that can find in the shards in the source TFRecord dataset into shards starting with
# the prefix `train-shard`
datasets:
  - train
  - val
  - test
  - predict
omitMissing: True  # skip missing TCEs in the TFRecords that exist in the dataset tables
nProcesses: 10  # number of processes used to create the new TFRecord dataset
n_examples_per_shard: 500  # number of examples in each shard in the new TFRecord dataset; min(n_examples_per_shard, n_total_examples)
# destination directory
dest_tfrec_dir: /Users/msaragoc/Projects/exoplanet_transit_classification/data/tfrecords/tess/tfrecords_tess_s1-s67_10-31-2023_1452_magshift_mission_adddiffimg_dataset_split
verbose: false
