# source TFRecord directory
srcTfrecDir: /Users/agiri1/Desktop/ExoBD_Datasets/shards

# destination TFRecord suffix name
destTfrecDir: /Users/agiri1/Desktop/ExoBD_Datasets/normed_shards

# normalization stats directory
normStats:
  scalar_params: /Users/agiri1/Desktop/ExoBD_Datasets/shards_norm_stats/train_scalarparam_norm_stats.npy
  centroid: /Users/agiri1/Desktop/ExoBD_Datasets/shards_norm_stats/train_centroid_norm_stats.npy
  diff_img: /Users/agiri1/Desktop/ExoBD_Datasets/shards_norm_stats/train_diffimg_norm_stats.npy

nProcesses: 10  # number of processes in parallel

# auxiliary parameters needed for normalization of some features
auxParams:
  nr_transit_durations: 5
  # 2 * 2.5 + 1,  # 2 * 4 + 1,  # number of transit durations (2*n+1, n on each side of the transit)
  num_bins_loc: 31  # 31, 201
  num_bins_glob: 301  # 301, 2001
