name: exoplnt_dl

dependencies:
  - aiofiles=22.1.0
  - aiosqlite=0.18.0
  - anyio=3.5.0
  - aom=3.6.0
  - appnope
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astropy=5.1
  - astroquery=0.4.6
  - asttokens=2.0.5
  - attrs=23.1.0
  - autograd=1.5
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - blosc=1.21.3
  - bokeh=3.3.4
  - boost-cpp=1.73.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.3.11
  - cairo=1.16.0
  - certifi=2024.6.2
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.3
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - expat=2.5.0
  - fbpca=1.0
  - flask=3.0.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - future=0.18.3
  - gcc
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.69.1
  - graphite2=1.3.14
  - graphviz=2.50.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gts=0.7.6
  - harfbuzz=4.3.0
  - html5lib=1.1
  - icu=68.1
  - idna=3.4
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - itsdangerous=2.2.0
  - jaraco.classes=3.2.1
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=1.23.4
  - jupyter_server_fileid=0.9.0
  - jupyter_server_ydoc=0.8.0
  - jupyter_ydoc=0.2.4
  - jupyterlab=3.6.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.22.0
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - keyring=23.13.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libavif=0.11.1
  - libboost=1.73.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang13=14.0.6
  - libcurl=8.2.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.4
  - libgd=2.3.3
  # - libgfortran=5.0.0
  - libgfortran
  # - libgfortran5=11.3.0
  - libgfortran5
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.15
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzopfli=1.0.3
  - lightkurve=2.4.2
  - llvm-openmp=14.0.6
  - lxml=4.9.3
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - memoization=0.4.0
  - mistune=0.8.4
  - mpi=1.0
  - mpi4py=3.1.4
  - mpich=3.3.2
  - munkres=1.1.4
  - mysql=5.7.24
  - nbclassic=0.5.5
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.2.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - oktopus=0.1.2
  - openjpeg=2.3.0
  - openpyxl=3.0.10
  - openssl=3.0.13
  - packaging=23.1
  - pandas=2.0.3
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - poppler=22.12.0
  - poppler-data=0.4.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pyerfa=2.0.0
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyvo=1.3
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - scikit-image=0.22.0
  - scikit-learn=1.2.2
  - scipy=1.11.1
  - send2trash=1.8.0
  - setuptools=68.0.0
  - sip=6.6.2
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - threadpoolctl=2.2.0
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.3.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - tzdata=2023c
  - uncertainties=3.1.7
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - xyzservices=2022.9.0
  - xz=5.4.2
  - y-py=0.5.9
  - yaml=0.2.5
  - ypy-websocket=0.8.2
  - zeromq=4.3.4
  - zfp=1.0.0
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - astunparse==1.6.3
      - cachetools==5.3.1
      - cloudpickle==2.2.1
      - configspace==0.7.1
      - dm-tree==0.1.8
      - flatbuffers==23.5.26
      - gast==0.4.0
      - google-auth==2.23.2
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.59.0
      - h5py==3.9.0
      - hpbandster==0.7.4
      - keras==2.13.1
      - libclang==16.0.6
      - markdown==3.4.4
      - ml-dtypes==0.2.0
      - more-itertools==10.1.0
      - netifaces==0.11.0
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - patsy==0.5.3
      - protobuf==4.24.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pydl==0.7.0
      - pydot==1.4.2
      - pyro4==4.82
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - serpent==1.41
      - statsmodels==0.14.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow==2.13.0
      - termcolor==2.3.0
      - typing-extensions==4.5.0
      - werkzeug==3.0.0
      - wrapt==1.14.1
