# source TFRecord directory
srcTfrecDir: null

# destination TFRecord suffix name
destTfrecDir: null

# normalization stats directory
normStats:
  scalar_params: exominer_pipeline/data/norm_stats/train_scalarparam_norm_stats.npy
  centroid: exominer_pipeline/data/norm_stats/train_centroid_norm_stats.npy
  diff_img: exominer_pipeline/data/norm_stats/train_diffimg_norm_stats.npy
  # scalar_params: /data/norm_stats/train_scalarparam_norm_stats.npy
  # centroid: /data/norm_stats/train_centroid_norm_stats.npy
  # diff_img: /data/norm_stats/train_diffimg_norm_stats.npy

nProcesses: 1  # number of processes in parallel

#diff_img_data_shape: [5, 55, 55]  # set defined image size given that images are stored as encoded strings
diff_img_data_shape: [5, 33, 33]  # set defined image size given that images are stored as encoded strings
