output_dir: null
input_tce_csv_file: null
lc_data_dir: null
external_parallelization: true
using_exominer_pipeline: true
process_i: -1
n_shards: 1
n_processes: 1
random_seed: 24
ffi_data: false
shuffle: false
shuffle_seed: 24
satellite: tess
plot_figures: false
plot_prob: 0.001
num_bins_glob: 301
num_bins_loc: 31
bin_width_factor_loc: 0.16
num_durations: 2.5
dq_values_filter: null
get_momentum_dump: false
detrending_method: savitzky-golay
sg_sigma: 5
sg_max_poly_order: 8
sg_penalty_weight: 1
sg_break_tolerance: 5
sg_n_durations_win: 5
spline_bkspace_min: 0.5
spline_bkspace_max: 20
spline_bkspace_num: 20
spline_maxiter: 5
spline_penalty_coeff: 1.0
spline_outlier_cut: 3
gapWidth: 0.007
n_max_phases: 20
keep_odd_even_order: false
min_n_phases: 1
frac_it_cadences_thr: 0.5
phase_extend_method: copy_phases
quarter_sampling: false
gapped: false
gap_keep_overlap: true
gap_imputed: false
tr_dur_f: 2
px_coordinates: false
prefer_psfcentr: false
outlier_removal: true
outlier_removal_sigma: 20
outlier_removal_fill: false
p_min_tce: 0.2
k_harmonics: 5
p_max_obs: 54
downsampling_f: 2
smooth_filter_type: boxkernel
smooth_filter_w_f: 2
scalar_params:
- tce_depth
- tce_max_mult_ev
- tce_max_sngle_ev
- tce_model_chisq
- tce_maxmes
- tce_maxmesd
- wst_depth
- tce_ptemp_stat
- tce_albedo_stat
- tce_bin_oedp_stat
- tce_dikco_msky
- tce_dikco_msky_err
- tce_dicco_msky
- tce_dicco_msky_err
- tce_cap_stat
- tce_hap_stat
- boot_fap
- tce_sdens
- tce_steff
- tce_slogg
- tce_smet
- tce_sradius
- mag
- tce_prad
augmentation: false
num_examples_per_tce: 1
aug_noise_factor: 0.05
tce_min_err:
  tce_period: 6.39723e-09
  tce_duration: 0.000385
  tce_time0bk: 2.44455e-06
light_curve_extension: LIGHTCURVE
injected_group: null
scramble_type: null
invert: false
cadence_no_quarters_tbl_fp: null
