# source TFRecord directory
srcTfrecDir: null

# destination TFRecord suffix name
destTfrecDir: null

# normalization stats directory
normStats:
  scalar_params: /Users/msaragoc/Downloads/norm_stats/train_scalarparam_norm_stats.npy
  centroid: /Users/msaragoc/Downloads/norm_stats/train_centroid_norm_stats.npy
  diff_img: /Users/msaragoc/Downloads/norm_stats/train_diffimg_norm_stats.npy

nProcesses: 1  # number of processes in parallel

diff_img_data_shape: [5, 55, 55]  # set defined image size given that images are stored as encoded strings
