
# path to output directory used to save results
output_dir: null
# process results either from TESS SPOC 2-min "2min" or FFI "ffi" data
data_collection_mode: null
# path to CSV file with TIC IDs to generate results for
tic_ids_fp: null
# number of processes to run application in parallel
num_processes: -1
# number of jobs to split the TIC IDs through
num_jobs: -1
# set to "true" or "false". If "true", it will create a CSV file with URLs to the SPOC DV reports for each TCE in the
# queried TICs
download_spoc_data_products: 'false'
# path to a directory containing the light curve FITS files and DV XML files for the TIC IDs and sector runs that you
# want to query; set to "null" otherwise
external_data_repository: null

### FIXED RUN PARAMETERS ###
# path to configuration file used to preprocess light curve data into a TFRecord dataset
lc_preprocessing_config_fp: exominer_pipeline/config_lc_preprocessing.yaml
# attributes to show for each example in the TFRecord dataset table
data_fields_tfrec_tbl:
  uid: str
  target_id: int
  tce_plnt_num: int
  sector_run: str
# path to configuration file used to preprocess difference image data
diff_img_preprocessing_config_fp: exominer_pipeline/config_diff_img_preprocessing.yaml
# path to configuration file used to add difference image data to TFRecord dataset
diff_img_add_tfrecord_dataset_config_fp: exominer_pipeline/config_add_diff_img_tfrecords.yaml
# path to configuration file used to normalize features in TFRecord dataset
normalize_tfrec_data_config_fp: exominer_pipeline/config_normalize_data.yaml
exominer_models:
  exominer++_single: exominer_pipeline/data/exominer-plusplus_cv-iter0-model0_tess-spoc-2min-s1s67_tess-kepler.keras
  exominer++_cviter-mean-ensemble: exominer_pipeline/data/exominer-plusplus_cv-iter0-ensemble_tess-spoc-2min-s1s67_tess.keras
  exominer++_cv-super-mean-ensemble: exominer_pipeline/data/exominer-plusplus_cv-mean-ensemble_tess-spoc-2min-s1s67_tess-kepler.keras
# path to ExoMiner TensorFlow Keras model used to generate predictions
model_fp: exominer_pipeline/data/exominer-plusplus_cv-iter0-model0_tess-spoc-2min-s1s67_tess-kepler.keras
# path to configuration file used for running inference
predict_config_fp: exominer_pipeline/config_predict_model.yaml
