process_parallel: true  # set to true to run CV iterations in parallel (one per GPU); only useful when number of GPUs > 1
rnd_seed: 2  # random seed used to select the validation fold in each CV iteration
rank: 0
# new data set directory; results are saved here
output_dir:  null
# source TFRecord directory to be normalized
src_tfrec_dir:  /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/predict/
# list of file paths to the CV iterations folder with the normalization statistics to be used
# to normalize the data in the source TFRecord directory
# (i.e., ['/path/to/cv_iter_x/norm_stats/', 'path/to/cv_iter_y/norm_stats',...])
cv_folds_fps:
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_0/norm_stats/
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_1/norm_stats/
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_2/norm_stats/
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_3/norm_stats/
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_4/norm_stats/
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_5/norm_stats/
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_6/norm_stats/
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_7/norm_stats/
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_8/norm_stats/
  - /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/tfrecords/TESS/tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159_data/cv_tfrecords_tess_spoc_2min_s1-s67_9-24-2024_1159/tfrecords/eval_normalized_with_kepler_trainset/cv_iter_9/norm_stats/

norm_stats:
  scalar_params: train_scalarparam_norm_stats.npy
  centroid: train_centroid_norm_stats.npy
#  fdl_centroid: train_fdlcentroid_norm_stats.npy
  diff_img: train_diffimg_norm_stats.npy

norm_examples_params:
  # SET TO 1 WHEN RUNNING ON THE HECC
  n_processes_norm_data: 1  # number of processes to parallelize data normalization for each CV iteration

  aux_params: # online data augmentation parameters and needed for normalization of some features
    nr_transit_durations: 5  # number of transit durations in the local view
    num_bins_loc: 31  # number of bins for local view
    num_bins_glob: 301  # number of bins for global view
