- fc_global_flux
- fc_local_centroid
- fc_momentum_dump
- fc_flux_trend
- fc_flux_periodogram
- local_flux_fc_local_odd_even
- local_flux_fc_local_flux
- local_flux_fc_local_weak_secondary
- fc_local_unfolded_flux
- fc_diff_img
- fc_stellar_scalar
- fc_dv_tce_fit_scalar
- fc0
- fc1
- fc2
- fc3
- logits
