# source TFRecord directory
srcTfrecDir: null

# destination TFRecord suffix name
destTfrecDir: null

# normalization stats directory
normStats:
  scalar_params: /path/train_scalarparam_norm_stats.npy
  centroid: /path/train_centroid_norm_stats.npy
  diff_img: /path/train_diffimg_norm_stats.npy

nProcesses: 36  # number of processes in parallel

diff_img_data_shape: [5, 33, 33]  # set defined image size given that images are stored as encoded strings
