n_processes: 10  # number of parallel processes for each configuration run
n_jobs: 1  # number of jobs (each job evaluates n_config_runs / n_processes)
#run_parallel: false
# file path to table that contains scores for all examples across all configuration runs
runs_tbl_fp: /data5/tess_project/experiments/current_experiments/explainability/shap_1-11-2022/runs_tbl.csv
# file path to table that contains set of examples for which to compute the values
examples_tbl_fp: /data5/tess_project/experiments/current_experiments/explainability/shap_1-11-2022/examples_tbl.csv
# directory to which save the resulting tables
results_dir: /data5/tess_project/experiments/current_experiments/explainability/shap_1-11-2022/mc_results
# file path to file that contains configuration runs for which to compute MCs of features
config_runs_fp: /data5/tess_project/experiments/current_experiments/explainability/shap_1-11-2022/list_config_runs_no_gc-lc.npy
# features chosen to compute MC and final SHAP values
features: [
    gf,
    lf,
    oe,
  #  lc,
    gc-lc,
    wks,
    s,
    dvtf,
]