# experiment directory for the ephemeris matching run
exp_dir: /Users/msaragoc/Projects/exoplanet_transit_classification/experiments/ephemeris_matching/tces_spoc_dv_2mindata_s1-s68

# table with start and end timestamps per TIC for different sectors
sector_timestamps_tbl_fp: /Users/msaragoc/Projects/exoplanet_transit_classification/experiments/ephemeris_matching/all_sectors_times_btjd_start_end/all_sectors_times_btjd_start_end_s1-s67_9-25-2023_1538_processed.csv

# plot probability of binary pulse time series
plot_prob: 0.01

# sampling rate used to generate the binary pulse time series
sampling_interval: 0.00139  # ~ 2/60/24

# table of signals of interest (usually TCEs)
tbl_a_fp: /Users/msaragoc/Projects/exoplanet_transit_classification/experiments/ephemeris_matching/tess_spoc_tces_processed_1-23-2024.csv
# table of signals to be matched to those in table A (usually objects with dispositions)
tbl_b_fp: /Users/msaragoc/Projects/exoplanet_transit_classification/experiments/ephemeris_matching/tois_catalog/tois_exofop_processed_1-23-2024.csv

n_procs: 10  # number of parallel processes
n_jobs: 10  # number of jobs
