#res_dir:
n_splits: 10  # number of splits of PCs and AFPs
mislabeling_rate: 0  # rate of injected stochastic noise into the PC and AFP categories
rnd_seed: 3  # random seed
noise_label: MISLABELED  # designation for mislabel pseudo-class
# source TFRecord dataset
src_tfrec_dir: /data5/tess_project/Data/tfrecords/Kepler/Q1-Q17_DR25/tfrecordskeplerq1q17dr25-dv_g301-l31_5tr_spline_nongapped_4-6-2022_data/tfrecordskeplerq1q17dr25-dv_g301-l31_5tr_spline_nongapped_4-6-2022_uid_experiment-normalized
features:
  target_id:
    dtype: int64
  tce_plnt_num:
    dtype: int64
  label:
    dtype: str