# experiment directory for the ephemeris matching run
exp_dir: null

# table with start and end timestamps per TIC for different sectors
sector_timestamps_tbl_fp: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/experiments/ephemeris_matching/tess_spoc_ffi_start_end_timestamps_tics_lc_s36-s72_4-17-2024_1421/tess_spoc_ffi_start_end_timestamps_tics_lc_s36-s72_4-17-2024_1421.csv

# plot probability of binary pulse time series
plot_prob: 0.0001

# sampling rate used to generate the binary pulse time series
sampling_interval: 0.00139  # ~ 2/60/24

# table of signals of interest (usually TCEs)
tbl_a_fp: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/Ephemeris_tables/TESS/tess_spoc_ffi/tess_spoc_ffi_s36-s72_multisector_s56-s69_fromdvxml_11-22-2024_0942/tess_spoc_ffi_s36-s72_multisector_s56-s69_sfromdvxml_11-22-2024_0942_renamed_cols_added_uid_ruwe_ticstellar_label_features_adjusted.csv

# table of signals to be matched to those in table A (usually objects with dispositions)
tbl_b_fp: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/Ephemeris_tables/TESS/hlsp_tess-ebs_tess_lcf-ffi_s0001-s0026_tess_v1.0_cat_processed.csv

n_procs: 128  # number of parallel processes
n_jobs: 384  # number of jobs
