---
modes:
  test: # test on subset of target, sector_run pairs
    target_sector_runs:
      - [198242678, "14-19"]
      - [30034081, "7"]
      - [309528896, "1-39"]
      - [260647166, "1-13"]
    plot: False
  build:
    plot: False
setup:
  mode: "build"
  paths: # fps/dirs #TODO: remove test and remove plotdir
    log_dir: "/nobackup/jochoa4/work_dir/data/logging/build_TESS_exoplanet_dataset_07-24-2025_no_detrend/"
    data_dir: "/nobackup/jochoa4/work_dir/data/datasets/TESS_exoplanet_dataset_07-24-2025_no_detrend/"
    lcf_dir: "/nobackup/msaragoc/work_dir/Kepler-TESS_exoplanet/data/FITS_files/TESS/spoc_2min/lc" # read lcfs from dir
    tpf_dir: "/nobackup/jochoa4/TESS/fits_files/spoc_2min/tp/" # read tpfs from dir
    tce_tbl_fp: "/nobackup/jochoa4/work_dir/data/tables/tess_2min_tces_dv_s1-s68_all_msectors_11-29-2023_2157_newlabels_nebs_npcs_bds_ebsntps_to_unks.csv"
  tce_tbl:
    keep_tce_disps: ["EB", "KP", "CP", "NTP", "NEB", "NPC", "UNK"] # Use TCE info from disps
    keep_target_disps: ["EB", "KP", "CP", "NEB", "NPC", "NTP"] # Only search targets which have at least one TCE of type
  multiprocessing:
    job_chunk_size: 2 # number of (target, sector_runs) or targets to process per job. TODO: update this
    validate_chunks: True #TODO UPDATE
    num_processes: 8 #null => all available cores
  dataset_preproc_params:
    tce_example_disps: ["EB", "KP", "CP", "NTP", "NEB", "NPC"] # Extract examples corresponding to TCEs of disposition
    detrend_lc_flag: False
    n_durations_window: 5  # num of transit durations in each extracted window
    ex_it_mask_n_durations_window: 3  # num of tds to use for masking it points, for selecting OOT examples w/o overlap
    sg_it_mask_n_durations_window: 2  # num of tds to use for masking it points, for SG detrending
    weak_sec_mask_maxmes_thr: 0  # min maxmes threshold for masking weak secondary transits
    frac_valid_cadences_in_window_thr: 0.85
    frac_valid_cadences_it_thr: 0.85
    buffer_time: 30  # in mins, between it cadences and oot cadences (diff_img)
    # # days used to split timeseries into smaller segments if interval between cadences is larger than gap_width
    # gap_width: 0.75
    resampled_num_points: 100  # number of points in the window after resampling
    rnd_seed: 42
    # difference image data parameters
    size_img: [11, 11]  # resize images to this size
    f_size: [3, 3] # enlarge `size_img` by these factors; final dimensions are f_size * size_img
    center_target: False  # center target in images