# output directory for TFRecords data set
output_dir: null
# TCE table with examples to be preprocessed
input_tce_csv_file: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/Ephemeris_tables/TESS/tess_spoc_ffi/tess_spoc_ffi_s36-s72_multisector_s56-s69_fromdvxml_11-22-2024_0942/tess_spoc_ffi_s36-s72_multisector_s56-s69_sfromdvxml_11-22-2024_0942_renamed_cols_added_uid_ruwe_ticstellar_label.csv
# light curve FITS file directory
lc_data_dir: /home6/msaragoc/work_dir/Kepler-TESS_exoplanet/data/FITS_files/TESS/spoc_ffi/lc

using_mpi: true  # use MPI/GNU parallel; set to False to use Python multiprocessing Pool
process_i: -1  # process id; defined by MPI/GNU when `using_mpi` set to True
# multiprocessing Pool arguments; overwritten if `using_mpi` is set to True
n_shards: 10  # total number of TFRecord files; examples are split into `n_shards`; Should be >= than `n_processes`
n_processes: 10  # number of processes created by the Pool

random_seed: 24

ffi_data: true  # set to true for TESS SPOC FFI data

shuffle: false
shuffle_seed: 24

satellite: tess  # 'kepler' or 'tess'

# plot figures for different preprocessing steps
plot_figures: true
plot_prob: 0.001  # 0.1

num_bins_glob: 301  # number of bins in global views
num_bins_loc: 31  # number of bins in local views
# bin_width_factor_glob: 1 / num_bins_glob
bin_width_factor_loc: 0.16
num_durations: 2.5  # number of transit durations to include in the local view: 2 * num_durations

# set which types of anomalies to be excluded from the data based on the data quality array in the lc fits file
# set to null for no exclusion
# otherwise list all values that map to the corresponding anomalies to be excluded based on the dq array
dq_values_filter: null  # set to null
#  - 2
#  - 3

get_momentum_dump: true  # get momentum dump dq flag and generate feature data

# detrending
detrending_method: 'savitzky-golay'  # 'savitzky-golay' for Savitzky-Golay or 'spline' for spline detrending
# Saviztky-Golay parameters
sg_sigma: 5
sg_max_poly_order: 8
sg_penalty_weight: 1
sg_break_tolerance: 5
sg_n_durations_win: 5
# spline parameters
spline_bkspace_min: 0.5
spline_bkspace_max: 20
spline_bkspace_num: 20
spline_maxiter: 5
spline_penalty_coeff: 1.0
spline_outlier_cut: 3
# split arrays if consecutive cadences are more than gapWidth days apart (only used for spline detrending)
# 0.75; 0.007 corresponds to 10 minutes (to make it consistent with sg detrending that uses a factor of
# `sg_break_tolerance` * median(dt)), where median(dt) ~ 2 min
gapWidth: 0.007

# unfolded time series
n_max_phases: 20  # max amount of phases considered for phase split view
keep_odd_even_order: false  # keep alternating odd/even phases
min_n_phases: 1  # minimum number of phases that need to be available for a given example
frac_it_cadences_thr: 0.5  # minimum fraction of valid cadences to consider a phase as valid
# if 'zero_padding', baseline phases (i.e., full of ones) are added; if 'copy_phases', phases are copied starting from
# the beginning
phase_extend_method: copy_phases
quarter_sampling: false  # sample transits from different seasons for Kepler

# gapping other TCEs from the data
gapped: false
gap_keep_overlap: true  # if true, cadences that overlap between TCE of interest and other TCE are kept
gap_imputed: false  # fill in gapped cadences with Gaussian noise; other set them to NaNs

# transit duration factor -> transit_duration * f
tr_dur_f: 2
# primary buffer when gapping secondary
#primary_buffer_nsamples: 0  # (not used) # 2-min, 6 ffi, 2 kepler (NOT BEING USED CURRENTLY)

# if True, CCD module pixel coordinates are used. If False, pixel coordinates are transformed into RA and Dec
# (world coordinates)
px_coordinates: false
# use PSF centroid instead of FW centroid
prefer_psfcentr: false

# outlier removal in phase fold time series
outlier_removal: true
outlier_removal_sigma: 20
outlier_removal_fill: false

## pixel length # (not used)
#tess_px_scale: 21  # arcsec
#kepler_px_scale: 3.98  # arcsec

#sampling_rate_h: # (not used) number of cadences sampled per hour; Kepler (2); TESS 2-min (30); TESS FFI (varied!)
#  kepler: 2
#  tess: 6  # 2-min: 30; ffi-200s: 18, ffi-10min: 6... varied!
#tess_to_kepler_sampling_ratio: 3  # 2-min: 15; ffi-200s: 9, ffi-10min: 3... varied!

# lc periodogram
p_min_tce : 0.2  # in days, shortest period to measure
k_harmonics: 5  # shortest period is multiplied by `k_harmonics` to give max freq 1 / p_min_tce * k_harmonics
p_max_obs: 54  # in days, longest period to measure (min freq is 1 / p_max_obs)
downsampling_f: 2  # downsampling factor when computing frequency range
smooth_filter_type: boxkernel  # choose between 'boxkernel' and 'logmedian'
smooth_filter_w_f: 2  # width of smoothing filter

# scalar parameters that show up in the plots of the preprocessed views
scalar_params: [
  # 'tce_period',
  # 'tce_duration',
  # 'tce_time0bk',
#  'transit_depth',
  'tce_depth',
  'tce_max_mult_ev',
  'tce_max_sngle_ev',
#  'tce_robstat',
  'tce_model_chisq',
  # secondary parameters
  'tce_maxmes',
  'tce_maxmesd',
#  'wst_robstat',
  'wst_depth',
  'tce_ptemp_stat',
  'tce_albedo_stat',
  # odd-even
  'tce_bin_oedp_stat',
  # centroid
#    'tce_fwm_stat',
    'tce_dikco_msky',
    'tce_dikco_msky_err',
    'tce_dicco_msky',
    'tce_dicco_msky_err',
  # other diagnostics
    'tce_cap_stat',
    'tce_hap_stat',
#    'tce_rb_tcount0',
    'boot_fap',
  # stellar parameters
#    'tce_smass',
    'tce_sdens',
    'tce_steff',
    'tce_slogg',
    'tce_smet',
    'tce_sradius',
    'mag',
  # transit fit parameters
  # 'tce_impact',
    'tce_prad',
]

# data augmentation
augmentation: false
num_examples_per_tce: 1
aug_noise_factor: 0.05
tce_min_err:
  tce_period: 6.39723e-9
  tce_duration: 0.000385  # in days
  tce_time0bk: 2.44455e-6

light_curve_extension: LIGHTCURVE  # 'INJECTED LIGHTCURVE' or 'LIGHTCURVE' otherwise

# simulated Kepler data options
injected_group: null  # set to `inj1`, `inj2`, or `inj3` to read lightcurves files from pixel-level transit injection data groups or null otherwise
scramble_type: null  # choose between `SCR1`, `SCR2`, and `SCR3` groups or null for no scrambling
invert: false  # inverted group

# when scrambling, information about the cadence number for the different quarters is required; set to null if not using scrambling data
cadence_no_quarters_tbl_fp: null
