rank: null
rnd_seed: 2
paths:
  experiment_root_dir: null
  datasets_fps_yaml: /Users/agiri1/Desktop/ExoBD_Datasets/tess_kepler_norm_shards_6-27-2024_1217/dataset_fps.yaml
  hpo_dir: /Users/agiri1/Desktop/ExoBD_Datasets/hpo_merged_unfolded_7-5-2023
val_from_train: false
generate_csv_pred: true
data_fields:
  uid: string
  target_id: int_scalar
  tce_plnt_num: int_scalar
  label: string
  tce_period: float_scalar
  tce_duration: float_scalar
  tce_time0bk: float_scalar
  ruwe: float_scalar
  tce_prad: float_scalar
  tce_max_mult_ev: float_scalar
model_architecture: ExoMiner_JointLocalFlux
config:
  conv_branches: null
  scalar_branches:
    stellar:
    - tce_sdens_norm
    - tce_steff_norm
    - tce_smet_norm
    - tce_slogg_norm
    - tce_smass_norm
    - tce_sradius_norm
    dv_tce_fit:
    - boot_fap_norm
    - tce_cap_stat_norm
    - tce_hap_stat_norm
    - tce_period_norm
    secondary_scalars:
    - tce_ptemp_stat_norm
    - tce_albedo_stat_norm
    - tce_maxmes_norm
    - tce_prad_norm
  transformer_branches: null
  diff_img_branch: null
  use_transformer: false
  num_transformer_blocks: 2
  head_size: 256
  num_heads: 4
  ff_dim: 4
  dropout_rate_transformer: 0.03
  transformer_output: flat
  time_encoding: true
  global-num_units_transformer_fc_layers:
  - 4
  local-num_units_transformer_fc_layers:
  - 4
  dropout_rate_trans_fc: 0.03
  non_lin_fn: prelu
  pool_stride: 1
  kernel_stride: 1
  optimizer: Adam
  weight_initializer: null
  force_softmax: false
  decay_rate: null
  batch_norm: false
  multi_class: false
features_set:
  unfolded_local_flux_view_fluxnorm:
    dim:
    - 20
    - 31
    dtype: float
  tce_num_transits_norm:
    dim:
    - 1
    dtype: float
  global_flux_view_fluxnorm:
    dim:
    - 301
    - 1
    dtype: float
  global_flux_view_fluxnorm_var:
    dim:
    - 301
    - 1
    dtype: float
  local_flux_view_fluxnorm:
    dim:
    - 31
    - 1
    dtype: float
  local_flux_view_fluxnorm_var:
    dim:
    - 31
    - 1
    dtype: float
  tce_max_mult_ev_norm:
    dim:
    - 1
    dtype: float
  tce_max_sngle_ev_norm:
    dim:
    - 1
    dtype: float
  tce_robstat_norm:
    dim:
    - 1
    dtype: float
  tce_model_chisq_norm:
    dim:
    - 1
    dtype: float
  local_flux_odd_view_fluxnorm:
    dim:
    - 31
    - 1
    dtype: float
  local_flux_even_view_fluxnorm:
    dim:
    - 31
    - 1
    dtype: float
  local_flux_odd_view_fluxnorm_var:
    dim:
    - 31
    - 1
    dtype: float
  local_flux_even_view_fluxnorm_var:
    dim:
    - 31
    - 1
    dtype: float
  local_centr_view_std_noclip:
    dim:
    - 31
    - 1
    dtype: float
  local_centr_view_std_noclip_var:
    dim:
    - 31
    - 1
    dtype: float
  tce_dikco_msky_norm:
    dim:
    - 1
    dtype: float
  tce_dikco_msky_err_norm:
    dim:
    - 1
    dtype: float
  ruwe_norm:
    dim:
    - 1
    dtype: float
  mag_shift_norm:
    dim:
    - 1
    dtype: float
  local_weak_secondary_view_selfnorm:
    dim:
    - 31
    - 1
    dtype: float
  local_weak_secondary_view_selfnorm_var:
    dim:
    - 31
    - 1
    dtype: float
  tce_maxmes_norm:
    dim:
    - 1
    dtype: float
  wst_depth_norm:
    dim:
    - 1
    dtype: float
  tce_albedo_stat_norm:
    dim:
    - 1
    dtype: float
  tce_ptemp_stat_norm:
    dim:
    - 1
    dtype: float
  boot_fap_norm:
    dim:
    - 1
    dtype: float
  tce_cap_stat_norm:
    dim:
    - 1
    dtype: float
  tce_hap_stat_norm:
    dim:
    - 1
    dtype: float
  tce_sdens_norm:
    dim:
    - 1
    dtype: float
  tce_steff_norm:
    dim:
    - 1
    dtype: float
  tce_smet_norm:
    dim:
    - 1
    dtype: float
  tce_slogg_norm:
    dim:
    - 1
    dtype: float
  tce_smass_norm:
    dim:
    - 1
    dtype: float
  tce_sradius_norm:
    dim:
    - 1
    dtype: float
  tce_prad_norm:
    dim:
    - 1
    dtype: float
  tce_period_norm:
    dim:
    - 1
    dtype: float
  diff_imgs_std_trainset:
    dim:
    - 33
    - 33
    - 5
    dtype: float
  oot_imgs_std_trainset:
    dim:
    - 33
    - 33
    - 5
    dtype: float
  target_imgs:
    dim:
    - 33
    - 33
    - 5
    dtype: float
  quality:
    dim:
    - 5
    - 1
    dtype: float
feature_map: null
training:
  data_augmentation: false
  online_preprocessing_params:
    num_bins_global: 301
    num_bins_local: 31
    num_transit_dur: 5
  n_epochs: 20
  opt_metric: auc_roc
  batch_size: 32
  filter_data: null
  category_weights:
    CP: 0.01457
    KP: 0.01457
    PC: 0.01457
    BD: 0.98543
  sample_weights: false
  shuffle_buffer_size: 42000
label_field_name: label
evaluation:
  batch_size: 32
inference:
  batch_size: 32
callbacks:
  early_stopping:
    monitor: val_auc_roc
    min_delta: 0
    patience: 20
    verbose: 1
    mode: max
    baseline: null
    restore_best_weights: true
  tensorboard:
    histogram_freq: 1
    write_graph: true
    write_images: false
    update_freq: epoch
    profile_batch: 2
    embeddings_metadata: null
    embeddings_freq: 0
label_map:
  PC: 1
  KP: 1
  CP: 1
  BD: 0
datasets:
- train
- val
- test
plot_model: true
write_model_summary: true
verbose_model: 2
verbose: true
metrics:
  clf_thr: 0.5
  num_thr: 1000
