# choose columns to keep in the logits, margins and AUM tables
idx_cols:
  - target_id
  - tce_plnt_num
  - label
  - label_id
  - original_label
  - shard_name
  - dataset

# noise_label = 'MISLABELED'

n_epochs: 500  # number of epochs for which to compute AUM and related statistics

min_num_processes: 1  # minimum number of processes to split the computations

# experiment directory
experiment_dir_fp: /Users/msaragoc/OneDrive - NASA/Projects/exoplanet_transit_classification/experiments/label_noise_detection_aum/run_04-13-2022_1155/

# TCE table filepath; get extra/updated information from the TCE table
tce_tbl_fp: /Users/msaragoc/OneDrive - NASA/Projects/exoplanet_transit_classification/data/ephemeris_tables/kepler/q1-q17_dr25/11-17-2021_1243/q1_q17_dr25_tce_2020.09.28_10.36.22_stellar_koi_cfp_norobovetterlabels_renamedcols_nomissingval_symsecphase_cpkoiperiod_rba_cnt0n_valpc_modelchisqr_ruwe_magcat_uid.csv
