rank: null
rnd_seed: 2
paths:
  experiment_root_dir: null
  datasets_fps_yaml: /Users/agiri1/Desktop/ExoBD_Datasets/tess_kepler_norm_shards_6-27-2024_1217/datasets_fps.yaml
  hpo_dir: /Users/agiri1/Desktop/ExoBD_Datasets/hpo_merged_unfolded_7-5-2023
val_from_train: false
generate_csv_pred: true
data_fields:
  uid: string
  target_id: int_scalar
  tce_plnt_num: int_scalar
  label: string
  tce_period: float_scalar
  tce_duration: float_scalar
  tce_time0bk: float_scalar
  ruwe: float_scalar
  tce_prad: float_scalar
  tce_max_mult_ev: float_scalar
model_architecture: ExoMiner_JointLocalFlux
config:
  conv_branches:
    local_unfolded_flux:
      views:
      - unfolded_local_flux_view_fluxnorm
      scalars:
      - tce_num_transits_norm
    global_flux:
      views:
      - global_flux_view_fluxnorm
      - global_flux_view_fluxnorm_var
      scalars: null
    local_flux:
      views:
      - local_flux_view_fluxnorm
      - local_flux_view_fluxnorm_var
      scalars:
      - tce_max_mult_ev_norm
      - tce_max_sngle_ev_norm
      - tce_robstat_norm
      - tce_model_chisq_norm
    local_weak_secondary:
      views:
      - local_weak_secondary_view_selfnorm
      - local_weak_secondary_view_selfnorm_var
      scalars:
      - tce_ptemp_stat_norm
      - tce_albedo_stat_norm
      - tce_maxmes_norm
      - tce_prad_norm
    local_odd_even:
      views:
      - local_flux_odd_view_fluxnorm
      - local_flux_odd_view_fluxnorm_var
      - local_flux_even_view_fluxnorm
      - local_flux_even_view_fluxnorm_var
      scalars: null
  scalar_branches:
    stellar:
    - tce_sdens_norm
    - tce_steff_norm
    - tce_smet_norm
    - tce_slogg_norm
    - tce_smass_norm
    - tce_sradius_norm
    dv_tce_fit:
    - boot_fap_norm
    - tce_cap_stat_norm
    - tce_hap_stat_norm
    secondary_scalars:
    - tce_ptemp_stat_norm
    - tce_albedo_stat_norm
    - tce_maxmes_norm
  transformer_branches: null
  diff_img_branch: null
  use_transformer: false
  num_transformer_blocks: 2
  head_size: 256
  num_heads: 4
  ff_dim: 4
  dropout_rate_transformer: 0.03
  transformer_output: flat
  time_encoding: true
  global-num_units_transformer_fc_layers:
  - 4
  local-num_units_transformer_fc_layers:
  - 4
  dropout_rate_trans_fc: 0.03
  non_lin_fn: prelu
  pool_stride: 1
  kernel_stride: 1
  optimizer: Adam
  weight_initializer: null
  force_softmax: false
  decay_rate: null
  batch_norm: false
  multi_class: false
  conv_ls_per_block: 3
  dropout_rate: 0.021491238286347598
  dropout_rate_fc_conv: 0.1211390996398814
  init_conv_filters: 3
  init_fc_neurons: 512
  kernel_size_glob: 5
  kernel_size_loc: 6
  lr: 4.176171931455995e-05
  num_fc_conv_units: 3
  num_fc_layers: 4
  num_glob_conv_blocks: 2
  num_loc_conv_blocks: 2
  pool_size_glob: 8
  pool_size_loc: 4
  kernel_size_unfolded: 6
  kernel_size_centr: 5
  pool_size_unfolded: 4
  pool_size_centr: 4
  num_unfolded_conv_blocks: 2
  num_centr_conv_blocks: 2
  init_loc_conv_filters: 3
  init_glob_conv_filters: 3
  init_unfolded_conv_filters: 3
  init_centr_conv_filters: 3
  loc_conv_ls_per_block: 3
  glob_conv_ls_per_block: 3
  unfolded_conv_ls_per_block: 3
  centr_conv_ls_per_block: 3
features_set:
  unfolded_local_flux_view_fluxnorm:
    dim:
    - 20
    - 31
    dtype: float
  tce_num_transits_norm:
    dim:
    - 1
    dtype: float
  global_flux_view_fluxnorm:
    dim:
    - 301
    - 1
    dtype: float
  global_flux_view_fluxnorm_var:
    dim:
    - 301
    - 1
    dtype: float
  local_flux_view_fluxnorm:
    dim:
    - 31
    - 1
    dtype: float
  local_flux_view_fluxnorm_var:
    dim:
    - 31
    - 1
    dtype: float
  tce_max_mult_ev_norm:
    dim:
    - 1
    dtype: float
  tce_max_sngle_ev_norm:
    dim:
    - 1
    dtype: float
  tce_robstat_norm:
    dim:
    - 1
    dtype: float
  tce_model_chisq_norm:
    dim:
    - 1
    dtype: float
  local_flux_odd_view_fluxnorm:
    dim:
    - 31
    - 1
    dtype: float
  local_flux_even_view_fluxnorm:
    dim:
    - 31
    - 1
    dtype: float
  local_flux_odd_view_fluxnorm_var:
    dim:
    - 31
    - 1
    dtype: float
  local_flux_even_view_fluxnorm_var:
    dim:
    - 31
    - 1
    dtype: float
  local_centr_view_std_noclip:
    dim:
    - 31
    - 1
    dtype: float
  local_centr_view_std_noclip_var:
    dim:
    - 31
    - 1
    dtype: float
  tce_dikco_msky_norm:
    dim:
    - 1
    dtype: float
  tce_dikco_msky_err_norm:
    dim:
    - 1
    dtype: float
  ruwe_norm:
    dim:
    - 1
    dtype: float
  mag_shift_norm:
    dim:
    - 1
    dtype: float
  local_weak_secondary_view_selfnorm:
    dim:
    - 31
    - 1
    dtype: float
  local_weak_secondary_view_selfnorm_var:
    dim:
    - 31
    - 1
    dtype: float
  tce_maxmes_norm:
    dim:
    - 1
    dtype: float
  tce_albedo_stat_norm:
    dim:
    - 1
    dtype: float
  tce_ptemp_stat_norm:
    dim:
    - 1
    dtype: float
  boot_fap_norm:
    dim:
    - 1
    dtype: float
  tce_cap_stat_norm:
    dim:
    - 1
    dtype: float
  tce_hap_stat_norm:
    dim:
    - 1
    dtype: float
  tce_sdens_norm:
    dim:
    - 1
    dtype: float
  tce_steff_norm:
    dim:
    - 1
    dtype: float
  tce_smet_norm:
    dim:
    - 1
    dtype: float
  tce_slogg_norm:
    dim:
    - 1
    dtype: float
  tce_smass_norm:
    dim:
    - 1
    dtype: float
  tce_sradius_norm:
    dim:
    - 1
    dtype: float
  tce_prad_norm:
    dim:
    - 1
    dtype: float
  tce_period_norm:
    dim:
    - 1
    dtype: float
  diff_imgs_std_trainset:
    dim:
    - 33
    - 33
    - 5
    dtype: float
  oot_imgs_std_trainset:
    dim:
    - 33
    - 33
    - 5
    dtype: float
  target_imgs:
    dim:
    - 33
    - 33
    - 5
    dtype: float
  quality:
    dim:
    - 5
    - 1
    dtype: float
feature_map: null
training:
  data_augmentation: false
  online_preprocessing_params:
    num_bins_global: 301
    num_bins_local: 31
    num_transit_dur: 5
  n_models: 1
  n_epochs: 20
  opt_metric: auc_roc
  batch_size: 256
  filter_data: null
  category_weights:
    PC: 0.01457
    KP: 0.01457
    CP: 0.01457
    BD: 0.98543
  sample_weights: false
  shuffle_buffer_size: 42000
label_field_name: label
evaluation:
  batch_size: 32
inference:
  batch_size: 32
callbacks:
  early_stopping:
    monitor: val_auc_pr
    min_delta: 0
    patience: 20
    verbose: 1
    mode: max
    baseline: null
    restore_best_weights: true
  tensorboard:
    histogram_freq: 1
    write_graph: true
    write_images: false
    update_freq: epoch
    profile_batch: 2
    embeddings_metadata: null
    embeddings_freq: 0
label_map:
  PC: 0
  KP: 0
  CP: 0
  BD: 1
datasets:
- train
- val
- test
plot_model: true
write_model_summary: true
verbose_model: 2
verbose: true
metrics:
  clf_thr: 0.5
  num_thr: 1000
hpo_config_id: !!python/tuple
- 23
- 0
- 0
datasets_fps:
  test:
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00011-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00010-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00006-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00007-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00001-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00000-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00005-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00004-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00012-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00013-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00014-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00002-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00003-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00008-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - test-shard-00009-of-00014
  train:
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00013-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00012-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00027-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00026-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00019-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00018-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00004-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00005-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00030-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00031-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00003-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00002-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00009-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00008-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00014-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00015-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00020-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00021-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00007-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00006-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00024-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00025-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00010-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00011-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00023-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00022-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00029-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00028-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00017-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00016-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00000-of-00031
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - train-shard-00001-of-00031
  val:
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00005-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00004-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00012-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00013-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00014-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00002-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00003-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00008-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00009-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00011-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00010-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00006-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00007-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00001-of-00014
  - !!python/object/apply:pathlib.PosixPath
    - /
    - Users
    - agiri1
    - Desktop
    - ExoBD_Datasets
    - tess_kepler_norm_shards_6-27-2024_1217
    - val-shard-00000-of-00014
