conv_ls_per_block: 3
dropout_rate: 0.021491238286347598
dropout_rate_fc_conv: 0.1211390996398814
init_conv_filters: 3
init_fc_neurons: 512
kernel_size_glob: 5
kernel_size_loc: 6
lr: 4.176171931455995e-05
num_fc_conv_units: 3
num_fc_layers: 4
num_glob_conv_blocks: 2
num_loc_conv_blocks: 2
pool_size_glob: 8
pool_size_loc: 4
kernel_size_unfolded: 6
kernel_size_centr: 5
pool_size_unfolded: 4
pool_size_centr: 4
num_unfolded_conv_blocks: 2
num_centr_conv_blocks: 2
init_loc_conv_filters: 3
init_glob_conv_filters: 3
init_unfolded_conv_filters: 3
init_centr_conv_filters: 3
loc_conv_ls_per_block: 3
glob_conv_ls_per_block: 3
unfolded_conv_ls_per_block: 3
centr_conv_ls_per_block: 3
