# experiment directory for the ephemeris matching run
exp_dir: null

# table with start and end timestamps per TIC for different sectors
sector_timestamps_tbl_fp: path/to/sector/timestamps/tbl

# plot probability of binary pulse time series
plot_prob: 0.0001

# sampling rate used to generate the binary pulse time series
sampling_interval: 0.00139  # ~ 2/60/24

# table of signals of interest (usually TCEs)
tbl_a_fp: /path/to/tce/table

# table of signals to be matched to those in table A (usually objects with dispositions)
tbl_b_fp: /path/to/objects/table

n_procs: 128  # number of parallel processes
n_jobs: 384  # number of jobs
